version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile-dev
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
